// Package gomobile_bind is an autogenerated binder stub for package testpkg.
//   gobind -lang=go golang.org/x/mobile/bind/objc/testpkg
//
// File is generated by gobind. Do not edit.
package gomobile_bind

/*
#include <stdlib.h>
#include <stdint.h>
#include "seq.h"
#include "testpkg.h"

*/
import "C"

import (
	"golang.org/x/mobile/bind/objc/testpkg"
	_seq "golang.org/x/mobile/bind/seq"
)

// suppress the error if seq ends up unused
var _ = _seq.FromRefNum

type proxyNode _seq.Ref

//export proxytestpkg_Node_V_Set
func proxytestpkg_Node_V_Set(refnum C.int32_t, v C.nstring) {
	ref := _seq.FromRefNum(int32(refnum))
	_v := decodeString(v, false)
	ref.Get().(*testpkg.Node).V = _v
}

//export proxytestpkg_Node_V_Get
func proxytestpkg_Node_V_Get(refnum C.int32_t) C.nstring {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*testpkg.Node).V
	_v := encodeString(v, true)
	return _v
}

//export proxytestpkg_Node_Err_Set
func proxytestpkg_Node_Err_Set(refnum C.int32_t, v C.nstring) {
	ref := _seq.FromRefNum(int32(refnum))
	_v_str := decodeString(v, false)
	_v := toError(_v_str)
	ref.Get().(*testpkg.Node).Err = _v
}

//export proxytestpkg_Node_Err_Get
func proxytestpkg_Node_Err_Get(refnum C.int32_t) C.nstring {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*testpkg.Node).Err
	var _v_str string
	if v == nil {
		_v_str = ""
	} else {
		_v_str = v.Error()
	}
	_v := encodeString(_v_str, true)
	return _v
}

type proxyNullFieldStruct _seq.Ref

//export proxytestpkg_NullFieldStruct_F_Set
func proxytestpkg_NullFieldStruct_F_Set(refnum C.int32_t, v C.int32_t) {
	ref := _seq.FromRefNum(int32(refnum))
	// Must be a Go object
	_v_ref := _seq.FromRefNum(int32(v))
	_v := _v_ref.Get().(*testpkg.S)
	ref.Get().(*testpkg.NullFieldStruct).F = _v
}

//export proxytestpkg_NullFieldStruct_F_Get
func proxytestpkg_NullFieldStruct_F_Get(refnum C.int32_t) C.int32_t {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*testpkg.NullFieldStruct).F
	var _v C.int32_t = _seq.NullRefNum
	if v != nil {
		_v = C.int32_t(_seq.ToRefNum(v))
	}
	return _v
}

type proxyS _seq.Ref

//export proxytestpkg_S_X_Set
func proxytestpkg_S_X_Set(refnum C.int32_t, v C.double) {
	ref := _seq.FromRefNum(int32(refnum))
	_v := float64(v)
	ref.Get().(*testpkg.S).X = _v
}

//export proxytestpkg_S_X_Get
func proxytestpkg_S_X_Get(refnum C.int32_t) C.double {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*testpkg.S).X
	_v := C.double(v)
	return _v
}

//export proxytestpkg_S_Y_Set
func proxytestpkg_S_Y_Set(refnum C.int32_t, v C.double) {
	ref := _seq.FromRefNum(int32(refnum))
	_v := float64(v)
	ref.Get().(*testpkg.S).Y = _v
}

//export proxytestpkg_S_Y_Get
func proxytestpkg_S_Y_Get(refnum C.int32_t) C.double {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*testpkg.S).Y
	_v := C.double(v)
	return _v
}

//export proxytestpkg_S_Sum
func proxytestpkg_S_Sum(refnum C.int32_t) C.double {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*testpkg.S)
	res_0 := v.Sum()
	_res_0 := C.double(res_0)
	return _res_0
}

//export proxytestpkg_S_TryTwoStrings
func proxytestpkg_S_TryTwoStrings(refnum C.int32_t, param_first C.nstring, param_second C.nstring) C.nstring {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*testpkg.S)
	_param_first := decodeString(param_first, false)
	_param_second := decodeString(param_second, false)
	res_0 := v.TryTwoStrings(_param_first, _param_second)
	_res_0 := encodeString(res_0, true)
	return _res_0
}

type proxyStructThatStartsWithLetterBeforeZ _seq.Ref

//export proxytestpkg_StructThatStartsWithLetterBeforeZ_Value_Set
func proxytestpkg_StructThatStartsWithLetterBeforeZ_Value_Set(refnum C.int32_t, v C.int32_t) {
	ref := _seq.FromRefNum(int32(refnum))
	var _v testpkg.Z
	_v_ref := _seq.FromRefNum(int32(v))
	if _v_ref != nil {
		if _v_ref.Num < 0 { // go object
			_v = _v_ref.Get().(testpkg.Z)
		} else { // foreign object
			_v = (*proxytestpkg_Z)(_v_ref)
		}
	}
	ref.Get().(*testpkg.StructThatStartsWithLetterBeforeZ).Value = _v
}

//export proxytestpkg_StructThatStartsWithLetterBeforeZ_Value_Get
func proxytestpkg_StructThatStartsWithLetterBeforeZ_Value_Get(refnum C.int32_t) C.int32_t {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(*testpkg.StructThatStartsWithLetterBeforeZ).Value
	var _v C.int32_t = _seq.NullRefNum
	if v != nil {
		_v = C.int32_t(_seq.ToRefNum(v))
	}
	return _v
}

//export proxytestpkg_I_Error
func proxytestpkg_I_Error(refnum C.int32_t, param_triggerError C.char) C.nstring {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(testpkg.I)
	_param_triggerError := param_triggerError != 0
	res_0 := v.Error(_param_triggerError)
	var _res_0_str string
	if res_0 == nil {
		_res_0_str = ""
	} else {
		_res_0_str = res_0.Error()
	}
	_res_0 := encodeString(_res_0_str, true)
	return _res_0
}

//export proxytestpkg_I_StringError
func proxytestpkg_I_StringError(refnum C.int32_t, param_s C.nstring) (C.nstring, C.nstring) {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(testpkg.I)
	_param_s := decodeString(param_s, false)
	res_0, res_1 := v.StringError(_param_s)
	_res_0 := encodeString(res_0, true)
	var _res_1_str string
	if res_1 == nil {
		_res_1_str = ""
	} else {
		_res_1_str = res_1.Error()
	}
	_res_1 := encodeString(_res_1_str, true)
	return _res_0, _res_1
}

//export proxytestpkg_I_Times
func proxytestpkg_I_Times(refnum C.int32_t, param_v C.int32_t) C.int64_t {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(testpkg.I)
	_param_v := int32(param_v)
	res_0 := v.Times(_param_v)
	_res_0 := C.int64_t(res_0)
	return _res_0
}

type proxytestpkg_I _seq.Ref

func (p *proxytestpkg_I) Error(param_triggerError bool) error {
	var _param_triggerError C.char = 0
	if param_triggerError {
		_param_triggerError = 1
	}
	res := C.cproxytestpkg_I_Error(C.int32_t(p.Num), _param_triggerError)
	_res_str := decodeString(res, true)
	_res := toError(_res_str)
	return _res
}

func (p *proxytestpkg_I) StringError(param_s string) (string, error) {
	_param_s := encodeString(param_s, false)
	res := C.cproxytestpkg_I_StringError(C.int32_t(p.Num), _param_s)
	res_0 := decodeString(res.r0, true)
	res_1_str := decodeString(res.r1, true)
	res_1 := toError(res_1_str)
	return res_0, res_1
}

func (p *proxytestpkg_I) Times(param_v int32) int64 {
	_param_v := C.int32_t(param_v)
	res := C.cproxytestpkg_I_Times(C.int32_t(p.Num), _param_v)
	_res := int64(res)
	return _res
}

//export proxytestpkg_NullTest_Null
func proxytestpkg_NullTest_Null(refnum C.int32_t) C.int32_t {
	ref := _seq.FromRefNum(int32(refnum))
	v := ref.Get().(testpkg.NullTest)
	res_0 := v.Null()
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

type proxytestpkg_NullTest _seq.Ref

func (p *proxytestpkg_NullTest) Null() testpkg.NullTest {
	res := C.cproxytestpkg_NullTest_Null(C.int32_t(p.Num))
	var _res testpkg.NullTest
	_res_ref := _seq.FromRefNum(int32(res))
	if _res_ref != nil {
		if _res_ref.Num < 0 { // go object
			_res = _res_ref.Get().(testpkg.NullTest)
		} else { // foreign object
			_res = (*proxytestpkg_NullTest)(_res_ref)
		}
	}
	return _res
}

type proxytestpkg_Z _seq.Ref

//export var_settestpkg_IntVar
func var_settestpkg_IntVar(v C.nint) {
	_v := int(v)
	testpkg.IntVar = _v
}

//export var_gettestpkg_IntVar
func var_gettestpkg_IntVar() C.nint {
	v := testpkg.IntVar
	_v := C.nint(v)
	return _v
}

//export var_settestpkg_InterfaceVar
func var_settestpkg_InterfaceVar(v C.int32_t) {
	var _v testpkg.I
	_v_ref := _seq.FromRefNum(int32(v))
	if _v_ref != nil {
		if _v_ref.Num < 0 { // go object
			_v = _v_ref.Get().(testpkg.I)
		} else { // foreign object
			_v = (*proxytestpkg_I)(_v_ref)
		}
	}
	testpkg.InterfaceVar = _v
}

//export var_gettestpkg_InterfaceVar
func var_gettestpkg_InterfaceVar() C.int32_t {
	v := testpkg.InterfaceVar
	var _v C.int32_t = _seq.NullRefNum
	if v != nil {
		_v = C.int32_t(_seq.ToRefNum(v))
	}
	return _v
}

//export var_settestpkg_StringVar
func var_settestpkg_StringVar(v C.nstring) {
	_v := decodeString(v, false)
	testpkg.StringVar = _v
}

//export var_gettestpkg_StringVar
func var_gettestpkg_StringVar() C.nstring {
	v := testpkg.StringVar
	_v := encodeString(v, true)
	return _v
}

//export var_settestpkg_StructVar
func var_settestpkg_StructVar(v C.int32_t) {
	// Must be a Go object
	_v_ref := _seq.FromRefNum(int32(v))
	_v := _v_ref.Get().(*testpkg.Node)
	testpkg.StructVar = _v
}

//export var_gettestpkg_StructVar
func var_gettestpkg_StructVar() C.int32_t {
	v := testpkg.StructVar
	var _v C.int32_t = _seq.NullRefNum
	if v != nil {
		_v = C.int32_t(_seq.ToRefNum(v))
	}
	return _v
}

//export proxytestpkg__BytesAppend
func proxytestpkg__BytesAppend(param_a C.nbyteslice, param_b C.nbyteslice) C.nbyteslice {
	_param_a := toSlice(param_a, false)
	_param_b := toSlice(param_b, false)
	res_0 := testpkg.BytesAppend(_param_a, _param_b)
	_res_0 := fromSlice(res_0, true)
	return _res_0
}

//export proxytestpkg__CallIError
func proxytestpkg__CallIError(param_i C.int32_t, param_triggerError C.char) C.nstring {
	var _param_i testpkg.I
	_param_i_ref := _seq.FromRefNum(int32(param_i))
	if _param_i_ref != nil {
		if _param_i_ref.Num < 0 { // go object
			_param_i = _param_i_ref.Get().(testpkg.I)
		} else { // foreign object
			_param_i = (*proxytestpkg_I)(_param_i_ref)
		}
	}
	_param_triggerError := param_triggerError != 0
	res_0 := testpkg.CallIError(_param_i, _param_triggerError)
	var _res_0_str string
	if res_0 == nil {
		_res_0_str = ""
	} else {
		_res_0_str = res_0.Error()
	}
	_res_0 := encodeString(_res_0_str, true)
	return _res_0
}

//export proxytestpkg__CallIStringError
func proxytestpkg__CallIStringError(param_i C.int32_t, param_s C.nstring) (C.nstring, C.nstring) {
	var _param_i testpkg.I
	_param_i_ref := _seq.FromRefNum(int32(param_i))
	if _param_i_ref != nil {
		if _param_i_ref.Num < 0 { // go object
			_param_i = _param_i_ref.Get().(testpkg.I)
		} else { // foreign object
			_param_i = (*proxytestpkg_I)(_param_i_ref)
		}
	}
	_param_s := decodeString(param_s, false)
	res_0, res_1 := testpkg.CallIStringError(_param_i, _param_s)
	_res_0 := encodeString(res_0, true)
	var _res_1_str string
	if res_1 == nil {
		_res_1_str = ""
	} else {
		_res_1_str = res_1.Error()
	}
	_res_1 := encodeString(_res_1_str, true)
	return _res_0, _res_1
}

//export proxytestpkg__CallSSum
func proxytestpkg__CallSSum(param_s C.int32_t) C.double {
	// Must be a Go object
	_param_s_ref := _seq.FromRefNum(int32(param_s))
	_param_s := _param_s_ref.Get().(*testpkg.S)
	res_0 := testpkg.CallSSum(_param_s)
	_res_0 := C.double(res_0)
	return _res_0
}

//export proxytestpkg__CallWithNull
func proxytestpkg__CallWithNull(param_p0 C.int32_t, param_nuller C.int32_t) C.char {
	var _param_p0 testpkg.NullTest
	_param_p0_ref := _seq.FromRefNum(int32(param_p0))
	if _param_p0_ref != nil {
		if _param_p0_ref.Num < 0 { // go object
			_param_p0 = _param_p0_ref.Get().(testpkg.NullTest)
		} else { // foreign object
			_param_p0 = (*proxytestpkg_NullTest)(_param_p0_ref)
		}
	}
	var _param_nuller testpkg.NullTest
	_param_nuller_ref := _seq.FromRefNum(int32(param_nuller))
	if _param_nuller_ref != nil {
		if _param_nuller_ref.Num < 0 { // go object
			_param_nuller = _param_nuller_ref.Get().(testpkg.NullTest)
		} else { // foreign object
			_param_nuller = (*proxytestpkg_NullTest)(_param_nuller_ref)
		}
	}
	res_0 := testpkg.CallWithNull(_param_p0, _param_nuller)
	var _res_0 C.char = 0
	if res_0 {
		_res_0 = 1
	}
	return _res_0
}

//export proxytestpkg__CollectS
func proxytestpkg__CollectS(param_want C.nint, param_timeoutSec C.nint) C.nint {
	_param_want := int(param_want)
	_param_timeoutSec := int(param_timeoutSec)
	res_0 := testpkg.CollectS(_param_want, _param_timeoutSec)
	_res_0 := C.nint(res_0)
	return _res_0
}

//export proxytestpkg__Echo
func proxytestpkg__Echo(param_s C.nstring) C.nstring {
	_param_s := decodeString(param_s, false)
	res_0 := testpkg.Echo(_param_s)
	_res_0 := encodeString(res_0, true)
	return _res_0
}

//export proxytestpkg__GC
func proxytestpkg__GC() {
	testpkg.GC()
}

//export proxytestpkg__Hello
func proxytestpkg__Hello(param_s C.nstring) C.nstring {
	_param_s := decodeString(param_s, false)
	res_0 := testpkg.Hello(_param_s)
	_res_0 := encodeString(res_0, true)
	return _res_0
}

//export proxytestpkg__Hi
func proxytestpkg__Hi() {
	testpkg.Hi()
}

//export proxytestpkg__Int
func proxytestpkg__Int(param_x C.int32_t) {
	_param_x := int32(param_x)
	testpkg.Int(_param_x)
}

//export proxytestpkg__Multiply
func proxytestpkg__Multiply(param_idx C.int32_t, param_val C.int32_t) C.int64_t {
	_param_idx := int32(param_idx)
	_param_val := int32(param_val)
	res_0 := testpkg.Multiply(_param_idx, _param_val)
	_res_0 := C.int64_t(res_0)
	return _res_0
}

//export proxytestpkg__NewI
func proxytestpkg__NewI() C.int32_t {
	res_0 := testpkg.NewI()
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxytestpkg__NewNode
func proxytestpkg__NewNode(param_name C.nstring) C.int32_t {
	_param_name := decodeString(param_name, false)
	res_0 := testpkg.NewNode(_param_name)
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxytestpkg__NewNullFieldStruct
func proxytestpkg__NewNullFieldStruct() C.int32_t {
	res_0 := testpkg.NewNullFieldStruct()
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxytestpkg__NewNullInterface
func proxytestpkg__NewNullInterface() C.int32_t {
	res_0 := testpkg.NewNullInterface()
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxytestpkg__NewNullStruct
func proxytestpkg__NewNullStruct() C.int32_t {
	res_0 := testpkg.NewNullStruct()
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxytestpkg__NewS
func proxytestpkg__NewS(param_x C.double, param_y C.double) C.int32_t {
	_param_x := float64(param_x)
	_param_y := float64(param_y)
	res_0 := testpkg.NewS(_param_x, _param_y)
	var _res_0 C.int32_t = _seq.NullRefNum
	if res_0 != nil {
		_res_0 = C.int32_t(_seq.ToRefNum(res_0))
	}
	return _res_0
}

//export proxytestpkg__ReadIntoByteArray
func proxytestpkg__ReadIntoByteArray(param_s C.nbyteslice) (C.nint, C.nstring) {
	_param_s := toSlice(param_s, false)
	res_0, res_1 := testpkg.ReadIntoByteArray(_param_s)
	_res_0 := C.nint(res_0)
	var _res_1_str string
	if res_1 == nil {
		_res_1_str = ""
	} else {
		_res_1_str = res_1.Error()
	}
	_res_1 := encodeString(_res_1_str, true)
	return _res_0, _res_1
}

//export proxytestpkg__RegisterI
func proxytestpkg__RegisterI(param_idx C.int32_t, param_i C.int32_t) {
	_param_idx := int32(param_idx)
	var _param_i testpkg.I
	_param_i_ref := _seq.FromRefNum(int32(param_i))
	if _param_i_ref != nil {
		if _param_i_ref.Num < 0 { // go object
			_param_i = _param_i_ref.Get().(testpkg.I)
		} else { // foreign object
			_param_i = (*proxytestpkg_I)(_param_i_ref)
		}
	}
	testpkg.RegisterI(_param_idx, _param_i)
}

//export proxytestpkg__ReturnsError
func proxytestpkg__ReturnsError(param_b C.char) (C.nstring, C.nstring) {
	_param_b := param_b != 0
	res_0, res_1 := testpkg.ReturnsError(_param_b)
	_res_0 := encodeString(res_0, true)
	var _res_1_str string
	if res_1 == nil {
		_res_1_str = ""
	} else {
		_res_1_str = res_1.Error()
	}
	_res_1 := encodeString(_res_1_str, true)
	return _res_0, _res_1
}

//export proxytestpkg__StringDup
func proxytestpkg__StringDup(param_s C.nstring) C.nstring {
	_param_s := decodeString(param_s, false)
	res_0 := testpkg.StringDup(_param_s)
	_res_0 := encodeString(res_0, true)
	return _res_0
}

//export proxytestpkg__Sum
func proxytestpkg__Sum(param_x C.int64_t, param_y C.int64_t) C.int64_t {
	_param_x := int64(param_x)
	_param_y := int64(param_y)
	res_0 := testpkg.Sum(_param_x, _param_y)
	_res_0 := C.int64_t(res_0)
	return _res_0
}

//export proxytestpkg__UnregisterI
func proxytestpkg__UnregisterI(param_idx C.int32_t) {
	_param_idx := int32(param_idx)
	testpkg.UnregisterI(_param_idx)
}
