// Objective-C API for talking to golang.org/x/mobile/bind/objc/testpkg Go package.
//   gobind -lang=objc golang.org/x/mobile/bind/objc/testpkg
//
// File is generated by gobind. Do not edit.

#ifndef __testpkg_H__
#define __testpkg_H__

#include <stdint.h>
#include <objc/objc.h>
nstring cproxytestpkg_I_Error(int32_t refnum, char triggerError);

typedef struct cproxytestpkg_I_StringError_return {
	nstring r0;
	nstring r1;
} cproxytestpkg_I_StringError_return;
struct cproxytestpkg_I_StringError_return cproxytestpkg_I_StringError(int32_t refnum, nstring s);

int64_t cproxytestpkg_I_Times(int32_t refnum, int32_t v);

int32_t cproxytestpkg_NullTest_Null(int32_t refnum);

#endif
