// JNI function headers for the Go <=> Java bridge.
//   gobind -lang=java 
//
// File is generated by gobind. Do not edit.

#ifndef __Universe_H__
#define __Universe_H__

#include <jni.h>

extern jclass proxy_class__error;
extern jmethodID proxy_class__error_cons;

nstring cproxy_error_Error(int32_t refnum);

#endif
