// Objective-C API for talking to  Go package.
//   gobind -lang=objc 
//
// File is generated by gobind. Do not edit.

#ifndef __GO__H__
#define __GO__H__

#include <stdint.h>
#include <objc/objc.h>
nstring cproxy_error_Error(int32_t refnum);

#endif
